### ISSUE TITLE
Upgrade SDK to OpenAPI v2

### ISSUE THREAD

**Issue by vincentdelitz** [corbado/corbado-php#24]
# Background
Due to the upgrade to OpenAPI v2, we need to adapt our PHP Backend SDK as well. We will cut down on the services to only three:
- sessions
- users
- identifiers

This implies some more changes as well (see below).

# TODO
- [x] Implement the three new services / cut the SDKs down to these three (see above).
- [x] Refactor session service to make JWT validation throw exceptions instead of returning false
- [x] Change the Corbado Backend API to "https://backendapi.cloud.corbado.io"
- [x] Update the respective README accordingly
- [x] Please check the code examples (if applicable) and see if we need to update things there as well:
   - [x] Blog post for PHP Symfony (https://www.corbado.com/blog/passkeys-php-symfony)
   - [x] Update the corresponding example app (https://github.com/corbado/example-passkeys-php-symfony)
   - [x] Blog post for PHP Laravel (https://www.corbado.com/blog/passkeys-php-laravel)
   - [x] Update the corresponding example app (https://github.com/corbado/example-passkeys-php-laravel)
   - [x] Wizard (https://app.corbado.com/`<project-ID>`/project-setup/php)
